name = "map"
compatibility_date = "2025-4-7"


[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "pnpm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"